version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=422193507691.dkr.ecr.us-east-1.amazonaws.com/paperless-aws
      - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Going to push docker image
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '{"name":"paperless-backend","imageUri":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - printf '%s' $REPOSITORY_URI:$IMAGE_TAG > imagename.txt
      
artifacts:
  files:
    - imagename.txt
    - imageDetail.json
    - appspec.yml
    - taskdef.json
    - scripts/pulldocker.sh