package com.engro.paperlessbackend.dao;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class NotificationDao {

	private static Logger logger = LoggerFactory.getLogger(TagDao.class);

	@Autowired
	JdbcTemplate jdbcTemplate;
	
	public int getMyChecklistsCount(String userId) {
		int count = 0;
		try {
			String sqlSelectQuery = ""
					+ "SELECT COUNT(*) "
					+ "FROM "
					+ "( "
					+ "        SELECT *, "
					+ "                CASE WHEN TEMP4.unit = 'MANUAL' "
					+ "                        AND "
					+ "                        ( "
					+ "                                start_time > (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                OR end_time < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                        ) "
					+ "                        AND TEMP4.checklist_schedule_id NOT IN (SELECT checklist_schedule_id FROM tbl_checklist_status_history) "
					+ "                        THEN '0' "
					+ "                     ELSE '1' "
					+ "                END "
					+ "        FROM "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_schedule "
					+ "                WHERE checklist_schedule_id "
					+ "                IN "
					+ "                ( "
					+ "                        SELECT checklist_schedule_id_fk FROM "
					+ "                        ( "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id_fk FROM tbl_checklist_schedule_claimed "
					+ "                                        WHERE tbl_checklist_schedule_claimed.user_id_fk = '" + userId + "' "
					+ "                                        AND tbl_checklist_schedule_claimed.checklist_schedule_id_fk "
					+ "                                        IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                                WHERE checklist_id_fk "
					+ "                                                IN "
					+ "                                                ( "
					+ "                                                       SELECT checklist_id "
					+ "                                                        FROM tbl_checklist "
					+ "                                                        WHERE is_deleted = 0 "
					+ "                                                        AND checklist_id "
					+ "                                                        IN "
					+ "                                                        ( "
					+ "                                                                SELECT checklist_id_fk FROM tbl_checklist_approver_user "
					+ "                                                                WHERE user_id_fk = '" + userId + "' "
					+ "                                                                AND workflow_level_id_fk = 1 "
					+ "                                                                UNION "
					+ "                                                                SELECT checklist_id_fk FROM tbl_checklist_approver_group "
					+ "                                                                WHERE workflow_level_id_fk = 1 "
					+ "                                                                AND group_id_fk "
					+ "                                                                IN "
					+ "                                                                ( "
					+ "                                                                        SELECT group_id_fk FROM tbl_user_group "
					+ "                                                                        WHERE user_id_fk = '" + userId + "' "
					+ "                                                                ) "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                        AND checklist_schedule_id_fk "
					+ "                                        NOT IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_schedule_id FROM tbl_checklist_status_history "
					+ "                                        ) "
					+ "                                ) "
					+ "                                UNION "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_status_history "
					+ "                                        WHERE workflow_level_id_fk = 1 "
					+ "                                        AND status_timestamp IN "
					+ "                                        ( "
					+ "                                                SELECT t_stamp status_timestamp FROM "
					+ "                                                ( "
					+ "                                                        SELECT checklist_schedule_id, "
					+ "                                                        MAX(status_timestamp) t_stamp "
					+ "                                                        FROM "
					+ "                                                        ( "
					+ "                                                                SELECT * FROM tbl_checklist_status_history "
					+ "                                                                WHERE checklist_schedule_id "
					+ "                                                                IN "
					+ "                                                                ( "
					+ "                                                                        SELECT checklist_schedule_id_fk "
					+ "                                                                        FROM tbl_checklist_schedule_claimed "
					+ "                                                                        WHERE tbl_checklist_schedule_claimed.user_id_fk = '" + userId + "' "
					+ "                                                                        AND tbl_checklist_schedule_claimed.checklist_schedule_id_fk "
					+ "                                                                        IN "
					+ "                                                                        ( "
					+ "                                                                                SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                                                                WHERE checklist_id_fk "
					+ "                                                                                IN "
					+ "                                                                                ( "
					+ "                                                                                        SELECT checklist_id "
					+ "                                                                                        FROM tbl_checklist "
					+ "                                                                                        WHERE is_deleted = 0 "
					+ "                                                                                        AND checklist_id "
					+ "                                                                                        IN "
					+ "                                                                                        ( "
					+ "                                                                                                SELECT checklist_id_fk FROM tbl_checklist_approver_user "
					+ "                                                                                                WHERE user_id_fk = '" + userId + "' "
					+ "                                                                                                AND workflow_level_id_fk = 1 "
					+ "                                                                                                UNION "
					+ "                                                                                                SELECT checklist_id_fk FROM tbl_checklist_approver_group "
					+ "                                                                                                WHERE workflow_level_id_fk = 1 "
					+ "                                                                                                AND group_id_fk "
					+ "                                                                                                IN "
					+ "                                                                                                ( "
					+ "                                                                                                        SELECT group_id_fk FROM tbl_user_group "
					+ "                                                                                                        WHERE user_id_fk = '" + userId + "' "
					+ "                                                                                                ) "
					+ "                                                                                        ) "
					+ "                                                                                ) "
					+ "                                                                        ) "
					+ "                                                               ) "
					+ "                                                       ) TEMP1 "
					+ "                                                       GROUP BY  checklist_schedule_id "
					+ "                                                )TEMP2 "
					+ "                                        ) "
					+ "                                ) "
					+ "                        )TEMP3 "
					+ "                ) "
					+ "        )TEMP4 "
					+ "        JOIN tbl_checklist "
					+ "        ON "
					+ "        tbl_checklist.checklist_id = TEMP4.checklist_id_fk "
					+ ")TEMP5 WHERE TEMP5.case = '1';";

			count = jdbcTemplate.queryForObject(sqlSelectQuery, Integer.class);
			
			logger.debug("SUCCESS");

		} catch (Exception e) {
			logger.error("[Exception] - [{}]", e);
		}
		return count;
	}
	
	public int getAssignedChecklistsCount(String userId) {
		int count = 0;
		try {
			String sqlSelectQuery = ""
					+ "SELECT COUNT(*) FROM tbl_checklist_schedule "
					+ "WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "AND unit != 'MANUAL' "
					+ "AND checklist_id_fk "
					+ "IN "
					+ "( "
					+ "        SELECT checklist_id FROM tbl_checklist "
					+ "        WHERE  is_deleted = 0 "
					+ "        AND checklist_id "
					+ "        IN "
					+ "        ( "
					+ "                SELECT checklist_id_fk FROM tbl_checklist_approver_user "
					+ "                WHERE user_id_fk = '" + userId + "' "
					+ "                AND workflow_level_id_fk = 1 "
					+ "                UNION "
					+ "                SELECT checklist_id_fk FROM tbl_checklist_approver_group "
					+ "                WHERE workflow_level_id_fk = 1 "
					+ "                AND group_id_fk "
					+ "                IN "
					+ "                ( "
					+ "                        SELECT group_id_fk FROM tbl_user_group "
					+ "                        WHERE user_id_fk = '" + userId + "' "
					+ "                ) "
					+ "        ) "
					+ ") "
					+ "AND checklist_schedule_id "
					+ "NOT IN "
					+ "( "
					+ "        SELECT checklist_schedule_id_fk FROM tbl_checklist_schedule_claimed "
					+ ");";

			count = jdbcTemplate.queryForObject(sqlSelectQuery, Integer.class);
			
			logger.debug("SUCCESS");

		} catch (Exception e) {
			logger.error("[Exception] - [{}]", e);
		}
		return count;
	}
	
	public int getReviewChecklistsCount(String userId) {
		int count = 0;
		try {
			String sqlSelectQuery = ""


					+ "SELECT COUNT(*) FROM "
					+ "( "
					+ "        SELECT * FROM tbl_checklist_status_history "
					+ "        WHERE "
					+ "        workflow_level_id_fk = 2 "
					+ "        AND "
					+ "        status_timestamp IN "
					+ "        ( "
					+ "                SELECT t_stamp status_timestamp FROM "
					+ "                ( "
					+ "                        SELECT checklist_schedule_id, "
					+ "                        MAX(status_timestamp) t_stamp "
					+ "                        FROM tbl_checklist_status_history "
					+ "                        WHERE checklist_schedule_id IN "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                AND checklist_id_fk IN "
					+ "                                ( "
					+ "                                        SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 2 "
					+ "                                                UNION "
					+ "                                                SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 2 AND group_id_fk IN "
					+ "                                                ( "
					+ "                                                        SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                        ) "
					+ "                        GROUP BY  checklist_schedule_id "
					+ "                ) TEMP1 "
					+ "        ) "
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =3 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 3 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 3 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =4 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 4 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 4 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =5 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 5 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 5 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =6 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 6 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 6 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =7 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 7 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 7 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =8 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 8 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 8 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =9 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 9 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 9 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =10 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 10 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 10 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =11 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 11 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 11 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =12 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 12 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 12 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =13 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 13 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 13 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =14 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 14 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 14 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =15 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 15 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 15 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =16 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 16 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 16 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =17 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 17 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 17 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =18 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 18 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 18 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =19 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 19 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 19 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =20 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 20 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 20 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =21 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 21 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 21 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =22 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 22 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 22 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =23 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 23 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 23 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =24 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 24 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 24 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =25 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 25 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 25 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =26 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 26 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 26 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =27 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 27 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 27 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =28 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 28 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 28 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "
					
					+ "        UNION "
					+ "        ( "
					+ "                SELECT * FROM tbl_checklist_status_history "
					+ "                WHERE "
					+ "                workflow_level_id_fk =29 "
					+ "                AND "
					+ "                status_timestamp IN "
					+ "                ( "
					+ "                        SELECT t_stamp status_timestamp FROM "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id, "
					+ "                                MAX(status_timestamp) t_stamp "
					+ "                                FROM tbl_checklist_status_history "
					+ "                                WHERE checklist_schedule_id IN "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                        WHERE start_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "                                        AND checklist_id_fk IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id FROM tbl_checklist  WHERE is_deleted = 0 AND checklist_id IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_user WHERE user_id_fk = '" + userId + "' AND workflow_level_id_fk = 29 "
					+ "                                                        UNION "
					+ "                                                        SELECT checklist_id_fk FROM tbl_checklist_approver_group WHERE workflow_level_id_fk = 29 AND group_id_fk IN "
					+ "                                                        ( "
					+ "                                                                SELECT group_id_fk FROM tbl_user_group WHERE user_id_fk = '" + userId + "' "
					+ "                                                        ) "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                                GROUP BY  checklist_schedule_id "
					+ "                        ) TEMP1 "
					+ "                ) "
					+ "        ) "


					+ ")RESULT;";

			count = jdbcTemplate.queryForObject(sqlSelectQuery, Integer.class);
			
			logger.debug("SUCCESS");

		} catch (Exception e) {
			logger.error("[Exception] - [{}]", e);
		}
		return count;
	}
	
	public int getDueChecklistsCount(String userId) {
		int count = 0;
		try {
			String sqlSelectQuery = ""
					+ "SELECT COUNT(*) FROM tbl_checklist_schedule "
					+ "WHERE unit != 'MANUAL' "
					+ "AND end_timestamp > (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "AND checklist_schedule_id "
					+ "IN "
					+ "( "
					+ "        SELECT * FROM "
					+ "        ( "
					+ "                ( "
					+ "                        SELECT checklist_schedule_id_fk FROM tbl_checklist_schedule_claimed "
					+ "                        WHERE tbl_checklist_schedule_claimed.user_id_fk = '" + userId + "' "
					+ "                        AND tbl_checklist_schedule_claimed.checklist_schedule_id_fk "
					+ "                        IN "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                WHERE checklist_id_fk "
					+ "                                IN "
					+ "                                ( "
					+ "                                        SELECT checklist_id FROM tbl_checklist "
					+ "                                        WHERE  is_deleted = 0 "
					+ "                                        AND checklist_id "
					+ "                                        IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id_fk FROM tbl_checklist_approver_user "
					+ "                                                WHERE user_id_fk = '" + userId + "' "
					+ "                                                AND workflow_level_id_fk = 1 "
					+ "                                                UNION "
					+ "                                                SELECT checklist_id_fk FROM tbl_checklist_approver_group "
					+ "                                                WHERE workflow_level_id_fk = 1 "
					+ "                                                AND group_id_fk "
					+ "                                                IN "
					+ "                                                ( "
					+ "                                                        SELECT group_id_fk FROM tbl_user_group "
					+ "                                                        WHERE user_id_fk = '" + userId + "' "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                        ) "
					+ "                        AND checklist_schedule_id_fk "
					+ "                        NOT IN "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id FROM tbl_checklist_status_history "
					+ "                        ) "
					+ "                ) "
					+ "                UNION "
					+ "                ( "
					+ "                        SELECT checklist_schedule_id FROM tbl_checklist_status_history "
					+ "                        WHERE workflow_level_id_fk = 1 "
					+ "                        AND status_timestamp IN "
					+ "                        ( "
					+ "                                SELECT t_stamp status_timestamp FROM "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id, "
					+ "                                        MAX(status_timestamp) t_stamp "
					+ "                                        FROM "
					+ "                                        ( "
					+ "                                                SELECT * FROM tbl_checklist_status_history "
					+ "                                                WHERE checklist_schedule_id "
					+ "                                                IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_schedule_id_fk "
					+ "                                                        FROM tbl_checklist_schedule_claimed "
					+ "                                                        WHERE tbl_checklist_schedule_claimed.user_id_fk = '" + userId + "' "
					+ "                                                        AND tbl_checklist_schedule_claimed.checklist_schedule_id_fk "
					+ "                                                        IN "
					+ "                                                        ( "
					+ "                                                                SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                                                WHERE checklist_id_fk "
					+ "                                                                IN "
					+ "                                                                ( "
					+ "                                                                        SELECT checklist_id FROM tbl_checklist "
					+ "                                                                        WHERE  is_deleted = 0 "
					+ "                                                                        AND checklist_id "
					+ "                                                                        IN "
					+ "                                                                        ( "
					+ "                                                                                SELECT checklist_id_fk FROM tbl_checklist_approver_user "
					+ "                                                                                WHERE user_id_fk = '" + userId + "' "
					+ "                                                                                AND workflow_level_id_fk = 1 "
					+ "                                                                                UNION "
					+ "                                                                                SELECT checklist_id_fk FROM tbl_checklist_approver_group "
					+ "                                                                                WHERE workflow_level_id_fk = 1 "
					+ "                                                                                AND group_id_fk "
					+ "                                                                                IN "
					+ "                                                                                ( "
					+ "                                                                                        SELECT group_id_fk FROM tbl_user_group "
					+ "                                                                                        WHERE user_id_fk = '" + userId + "' "
					+ "                                                                                ) "
					+ "                                                                        ) "
					+ "                                                                ) "
					+ "                                                        ) "
					+ "                                               ) "
					+ "                                       ) TEMP1 "
					+ "                                       GROUP BY  checklist_schedule_id "
					+ "                                )TEMP2 "
					+ "                        ) "
					+ "                ) "
					+ "        )RESULT "
					+ ");";

			count = jdbcTemplate.queryForObject(sqlSelectQuery, Integer.class);
			
			logger.debug("SUCCESS");

		} catch (Exception e) {
			logger.error("[Exception] - [{}]", e);
		}
		return count;
	}
	
	public int getOverdueChecklistsCount(String userId) {
		int count = 0;
		try {
			String sqlSelectQuery = ""
					+ "SELECT COUNT(*) FROM tbl_checklist_schedule "
					+ "WHERE unit != 'MANUAL' "
					+ "AND end_timestamp < (SELECT ((EXTRACT(epoch FROM now())::bigint) * 1000)) "
					+ "AND checklist_schedule_id "
					+ "IN "
					+ "( "
					+ "        SELECT * FROM "
					+ "        ( "
					+ "                ( "
					+ "                        SELECT checklist_schedule_id_fk FROM tbl_checklist_schedule_claimed "
					+ "                        WHERE tbl_checklist_schedule_claimed.user_id_fk = '" + userId + "' "
					+ "                        AND tbl_checklist_schedule_claimed.checklist_schedule_id_fk "
					+ "                        IN "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                WHERE checklist_id_fk "
					+ "                                IN "
					+ "                                ( "
					+ "                                        SELECT checklist_id FROM tbl_checklist "
					+ "                                        WHERE  is_deleted = 0 "
					+ "                                        AND checklist_id "
					+ "                                        IN "
					+ "                                        ( "
					+ "                                                SELECT checklist_id_fk FROM tbl_checklist_approver_user "
					+ "                                                WHERE user_id_fk = '" + userId + "' "
					+ "                                                AND workflow_level_id_fk = 1 "
					+ "                                                UNION "
					+ "                                                SELECT checklist_id_fk FROM tbl_checklist_approver_group "
					+ "                                                WHERE workflow_level_id_fk = 1 "
					+ "                                                AND group_id_fk "
					+ "                                                IN "
					+ "                                                ( "
					+ "                                                        SELECT group_id_fk FROM tbl_user_group "
					+ "                                                        WHERE user_id_fk = '" + userId + "' "
					+ "                                                ) "
					+ "                                        ) "
					+ "                                ) "
					+ "                        ) "
					+ "                        AND checklist_schedule_id_fk "
					+ "                        NOT IN "
					+ "                        ( "
					+ "                                SELECT checklist_schedule_id FROM tbl_checklist_status_history "
					+ "                        ) "
					+ "                ) "
					+ "                UNION "
					+ "                ( "
					+ "                        SELECT checklist_schedule_id FROM tbl_checklist_status_history "
					+ "                        WHERE workflow_level_id_fk = 1 "
					+ "                        AND status_timestamp IN "
					+ "                        ( "
					+ "                                SELECT t_stamp status_timestamp FROM "
					+ "                                ( "
					+ "                                        SELECT checklist_schedule_id, "
					+ "                                        MAX(status_timestamp) t_stamp "
					+ "                                        FROM "
					+ "                                        ( "
					+ "                                                SELECT * FROM tbl_checklist_status_history "
					+ "                                                WHERE checklist_schedule_id "
					+ "                                                IN "
					+ "                                                ( "
					+ "                                                        SELECT checklist_schedule_id_fk "
					+ "                                                        FROM tbl_checklist_schedule_claimed "
					+ "                                                        WHERE tbl_checklist_schedule_claimed.user_id_fk = '" + userId + "' "
					+ "                                                        AND tbl_checklist_schedule_claimed.checklist_schedule_id_fk "
					+ "                                                        IN "
					+ "                                                        ( "
					+ "                                                                SELECT checklist_schedule_id FROM tbl_checklist_schedule "
					+ "                                                                WHERE checklist_id_fk "
					+ "                                                                IN "
					+ "                                                                ( "
					+ "                                                                        SELECT checklist_id FROM tbl_checklist "
					+ "                                                                        WHERE  is_deleted = 0 "
					+ "                                                                        AND checklist_id "
					+ "                                                                        IN "
					+ "                                                                        ( "
					+ "                                                                                SELECT checklist_id_fk FROM tbl_checklist_approver_user "
					+ "                                                                                WHERE user_id_fk = '" + userId + "' "
					+ "                                                                                AND workflow_level_id_fk = 1 "
					+ "                                                                                UNION "
					+ "                                                                                SELECT checklist_id_fk FROM tbl_checklist_approver_group "
					+ "                                                                                WHERE workflow_level_id_fk = 1 "
					+ "                                                                                AND group_id_fk "
					+ "                                                                                IN "
					+ "                                                                                ( "
					+ "                                                                                        SELECT group_id_fk FROM tbl_user_group "
					+ "                                                                                        WHERE user_id_fk = '" + userId + "' "
					+ "                                                                                ) "
					+ "                                                                        ) "
					+ "                                                                ) "
					+ "                                                        ) "
					+ "                                               ) "
					+ "                                       ) TEMP1 "
					+ "                                       GROUP BY  checklist_schedule_id "
					+ "                                )TEMP2 "
					+ "                        ) "
					+ "                ) "
					+ "        )RESULT "
					+ ");";

			count = jdbcTemplate.queryForObject(sqlSelectQuery, Integer.class);
			
			logger.debug("SUCCESS");

		} catch (Exception e) {
			logger.error("[Exception] - [{}]", e);
		}
		return count;
	}
}
